### ISSUE TITLE
I have some Question

### ISSUE THREAD

**Issue by mhwan** [arminkz/Reversi#2]
Hello, I was impressed with your project.
And I have questions.
In your project, i can see 4 AI players (AIplayerDynamic, AIplayerRealtime,AIplayerRealtime, AIplayerStatic ).
Can you tell me What's the difference between them?
And which brings smarter results?

Thank you.

**Comment by arminkz** [comment]
Hello,
i'm thankful for your attention.
you see `AIPlayerStatic` uses a fixed linear combination of different Evaluation scores mentioned in README, `AIPlayerDynamic` uses a hardcoded if condition to distinguish between early game, mid game and late game. `AIPlayerRealtime` uses the same linear combination but the coefficients are achieved using Machine Learning techniques for each round of the game. the `AIPlayerRealtimeKiller` is same as `AIPlayerRealtime` but it also uses Killer Move Detection.

on the paper the two latter AIs should perform better.
